// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBYhLNk4LoOfO7y0_SjjKbAuvQJoXqLs',
    appId: '1:655903468616:web:a93b7280a3cf54ce847c7d',
    messagingSenderId: '655903468616',
    projectId: 'tokofotocopy-app',
    authDomain: 'tokofotocopy-app.firebaseapp.com',
    storageBucket: 'tokofotocopy-app.firebasestorage.app',
    measurementId: 'G-CZ0KNM5PV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvfkdDgQMffwv32GBRvH3SFeqqxPWdQg',
    appId: '1:655903468616:android:62c80c75d84fd8bd847c7d',
    messagingSenderId: '655903468616',
    projectId: 'tokofotocopy-app',
    storageBucket: 'tokofotocopy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEbhGTZB27oxzWO12hGRT7L-iZw2NxXTg',
    appId: '1:655903468616:ios:c9fe39e09e02983c847c7d',
    messagingSenderId: '655903468616',
    projectId: 'tokofotocopy-app',
    storageBucket: 'tokofotocopy-app.firebasestorage.app',
    iosBundleId: 'com.example.fotocopyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEbhGTZB27oxzWO12hGRT7L-iZw2NxXTg',
    appId: '1:655903468616:ios:c9fe39e09e02983c847c7d',
    messagingSenderId: '655903468616',
    projectId: 'tokofotocopy-app',
    storageBucket: 'tokofotocopy-app.firebasestorage.app',
    iosBundleId: 'com.example.fotocopyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPBYhLNk4LoOfO7y0_SjjKbAuvQJoXqLs',
    appId: '1:655903468616:web:b9285ceb9ebea3e8847c7d',
    messagingSenderId: '655903468616',
    projectId: 'tokofotocopy-app',
    authDomain: 'tokofotocopy-app.firebaseapp.com',
    storageBucket: 'tokofotocopy-app.firebasestorage.app',
    measurementId: 'G-MDTD8BRD52',
  );
}
